// Generated by bridge-worker/scripts/generate-swift-patch-contract.mjs.
// Source: bridge-worker/src/patch-operations.json. Do not edit by hand.

enum FlowPatchContract {
    static let currentSchemaVersion = 3
    static let supportedSchemaVersions: Set<Int> = [2, 3]

    static let name = 200
    static let proposedRoutineName = 100
    static let exerciseNotes = 500
    static let constraintsNotes = 2000

    static let setsRange = 1...10
    static let repsRange = 1...100
    static let durationSecondsRange = 1...3600
    static let restSecondsRange = 0...900

    static let maximumRoutines = 50
    static let maximumSections = 50
    static let maximumExercisesPerSection = 100
}

extension FlowRoutinePatchOperation {
    enum Kind: String, Codable, Equatable, CaseIterable {
        case replaceExerciseReps
        case replaceExerciseSets
        case replaceTimedDuration
        case replaceRestBetweenSets
        case replaceRestAfterExercise
        case updateExerciseNotes
        case addExercise
        case removeExercise
        case moveExercise
        case replacePhaseOverride
        case renameRoutine
        case addSection
        case createRoutine

        var minimumSchemaVersion: Int {
            switch self {
            case .replaceExerciseReps: return 2
            case .replaceExerciseSets: return 2
            case .replaceTimedDuration: return 2
            case .replaceRestBetweenSets: return 2
            case .replaceRestAfterExercise: return 2
            case .updateExerciseNotes: return 2
            case .addExercise: return 2
            case .removeExercise: return 2
            case .moveExercise: return 2
            case .replacePhaseOverride: return 2
            case .renameRoutine: return 3
            case .addSection: return 3
            case .createRoutine: return 3
            }
        }
    }
}
